version: '2'

services:
  pmm-server:
    image: percona/pmm-server:latest
    container_name: pmm-server
    volumes:
      - /your/host/data:/srv
    entrypoint: /bin/true
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      - SERVER_USER=your_user
      - SERVER_PASSWORD=your_password
      - METRICS_RETENTION=720h
      - METRICS_MEMORY=4194304
      - METRICS_RESOLUTION=1s
      - QUERIES_RETENTION=30
